name: Patch Image via URL

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Recovery Image URL'
        default: 'https://www.mediafire.com/file/mgnyunol0ivq3f4/recovery.img/file#'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Gain file access
      uses: actions/checkout@v4.1.1
    
    - name: Fetch necessary packages
      run: |
         sudo apt update
         sudo apt install git wget lz4 tar openssl python3 -y
         
    - name: Download recovery image from URL
      run: |
         wget -O recovery.img ${{ github.event.inputs.image_url }}

    - name: Check if recovery.img exists
      run: |
         if [ ! -f "recovery.img" ]; then
           echo "Error: No recovery.img found!"
           exit 1
         fi

    - name: Start patching script
      run: |
         chmod +x magiskboot
         chmod +x patcher-minimal
         ./patcher-minimal

    - name: Upload patched image files
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/fastboot-patcher/fastboot-patcher/output/*.*
        name: Patched Recovery Image Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true
        
    - name: Upload keys for patched image
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/fastboot-patcher/fastboot-patcher/keys/*.*
        name: Patched Image Key Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true
